version: "3.8"

services:
  server:
    container_name: plp_server
    privileged: true
    image: phungthanhtu/plp_server:latest
    env_file:
      - ./.env
    ports:
      - "8080:80"
  engine:
    container_name: plp_engine
    privileged: true
    image: phungthanhtu/plp_engine:latest
    env_file:
      - ./.env
    volumes:
      - ./../../vm/sandboxes:/usr/local/etc/isolate/sandboxes/
      - ./../../engine:/engine
      - /engine/node_modules
      - ./../../vm/cg/cpuacct:/sys/fs/cgroup/cpuacct
      - ./../../vm/cg/memory:/sys/fs/cgroup/memory 
volumes:
    mssql: